openapi: 3.0.0
info:
  title: TaskManager API
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Локальный сервер
security:
  - CookieAuth: []

tags:
  - name: Auth
    description: Всё, что связано с пользователями и безопасностью
  - name: Tasks
    description: Управление задачами
  - name: Assignment
    description: Вся бизнес-логика назначения и распределения

paths:
  /auth/login:
    post:
      tags:
      - Auth
      summary: Аутентификация по логину и ключу
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthUser'
      responses:
        '200':
          description: Успешная аутентификация
          headers:
            Set-Cookie:
              description: Сессионый токен
              schema:
                type: string
                example: auth_token=abc123def456
              


  #/users GET POST
  #/users/{id} GET DELETE


  /tasks:
    post:
      tags:
      - Tasks
      summary: Создать задачу
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskDetail'
      responses:
        '200':
          description: Успешный ответ с id созданной задачи
          content:
              application/json:
                schema:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 14
  /tasks/{id}:
    get:
      tags:
      - Tasks
      summary: Получение деталей задачи по id
      parameters: 
        - $ref: '#/components/parameters/TaskIdRequest'
      responses:
        '200':
          description: Успешный ответ с информацией о задаче
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskDetail'
    delete:
      tags:
        - Tasks
      summary: Удаление задачи по id
      parameters: 
        - $ref: '#/components/parameters/TaskIdRequest'
      responses:
        '200':
          description: Успешный ответ с информацией о задаче
    #put!!!!!!!!!!!
      


                
components:
  securitySchemes:
    CookieAuth:
      type: apiKey
      in: cookie
      name: session_token
      description: Токен аутентификации в cookie. Получать токен через POST /auth/login!
  parameters:
    TaskIdRequest: 
      name: id
      description: ID задачи
      in: path
      required: true  
      schema:
        type: integer
        example: 4
        minimum: 1
  schemas:
    AuthUser:
      type: object
      properties:
        Login:
          type: string
          example: Konstantin
        Key:
          type: string
          example: nx9182!mx198MgfKL0S=AsL3
    TaskDetail:
      type: object
      properties:
        Id:
          description: id задачи
          type: integer
          example: 3
        Header:
          description: Краткое описание 
          type: string
          example: Сервис для авторизации
        Task:
          description: Подробное описание задачи (ТЗ)
          type: string
          example: Разработать сервис для авторизации. Срок 3 недели. Использовать postgres...
        Developers:
          description: Список с id разработчиков назначенных на задание
          type: array
          items:
            type: integer
          example: [1,23,5]