openapi: 3.0.0
info:
  title: TaskManager API
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Локальный сервер
security:
  - CookieAuth: []
tags:
  - name: Auth
    description: Всё, что связано с пользователями и безопасностью
  - name: Tasks
    description: Управление задачами
  - name: Assignment
    description: Вся бизнес-логика назначения и распределения
paths:
  /tasks:
    post:
      tags:
        - Tasks
      summary: Создать задачу
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskNew'
      responses:
        '200':
          description: Успешный ответ с id созданной задачи
          content:
            application/json:
              schema:
                type: object
                properties:
                  Id:
                    type: integer
                    example: 14
  /tasks/{id}:
    get:
      tags:
        - Tasks
      summary: Получение деталей задачи по id
      parameters:
        - $ref: '#/components/parameters/TaskIdRequest'
      responses:
        '200':
          description: Успешный ответ с информацией о задаче
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskDetail'
    delete:
      tags:
        - Tasks
      summary: Удаление задачи по id
      parameters:
        - $ref: '#/components/parameters/TaskIdRequest'
      responses:
        '200':
          description: Успешное удаление задачи
    put:
      tags:
        - Tasks
      summary: Обновить задачу
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskNew'
      responses:
        '200':
          description: Успех
  /auth:
    post:
      tags:
        - Auth
      summary: Аутентификация по логину и ключу
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Успешная аутентификация
          headers:
            Set-Cookie:
              description: Сессионый токен
              schema:
                type: string
                example: auth_token=abc123def456
  /users:
    get:
      tags:
        - Auth
      summary: Получение таблицы с пользователями (Id:Login)
      responses:
        '200':
          description: Успешный ответ с таблицей
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MapUser'
    post:
      tags:
        - Auth
      summary: Создать пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Успешно, возвращает Id созданного пользователя
          content:
            application/json:
              schema:
                type: object
                properties:
                  Id:
                    type: integer
                    example: 3
  /users/{id}:
    get:
      tags:
        - Auth
      summary: Получение деталей пользователя по id
      parameters:
        - $ref: '#/components/parameters/UserIdRequest'
      responses:
        '200':
          description: Успешный ответ с информацией о пользователе
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    delete:
      tags:
        - Auth
      summary: Пользователя по id
      parameters:
        - $ref: '#/components/parameters/UserIdRequest'
      responses:
        '200':
          description: Успешное удаление пользователя
  /assign:
    post:
      tags:
        - Assignment
      summary: Назначить задачу разработчику
      description: Если в качестве ключа 0 то задача назначается на всех доступных пользователях
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MapId'
      responses:
        '200':
          description: Успешное назначение
  /assign/user/{id}:
    get:
      tags:
        - Assignment
      summary: Задачи конкретного разработчика
      parameters:
        - $ref: '#/components/parameters/UserIdRequest'
      responses:
        '200':
          description: Успешный ответ с списком задач
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListId'
    delete:
      tags:
        - Assignment
      summary: Удаление задачи разработчика по его id
      parameters:
        - $ref: '#/components/parameters/UserIdRequest'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListId'
      responses:
        '200':
          description: Успешное удаление
components:
  securitySchemes:
    CookieAuth:
      type: apiKey
      in: cookie
      name: session_token
      description: Токен аутентификации в cookie. Получать токен через POST /auth/login!
  schemas:
    TaskNew:
      type: object
      properties:
        Header:
          description: Краткое описание
          type: string
          example: Сервис для авторизации
        Task:
          description: Подробное описание задачи (ТЗ)
          type: string
          example: Разработать сервис для авторизации. Срок 3 недели. Использовать postgres...
    TaskDetail:
      type: object
      properties:
        Id:
          description: id задачи
          type: integer
          example: 3
        Header:
          description: Краткое описание
          type: string
          example: Сервис для авторизации
        Task:
          description: Подробное описание задачи (ТЗ)
          type: string
          example: Разработать сервис для авторизации. Срок 3 недели. Использовать postgres...
        Developers:
          description: Список с id разработчиков назначенных на задание
          type: array
          items:
            type: integer
          example:
            - 1
            - 23
            - 5
    User:
      type: object
      properties:
        Login:
          type: string
          example: Konstantin
        Key:
          type: string
          example: nx9182!mx198MgfKL0S=AsL3
    MapUser:
      type: object
      additionalProperties:
        type: string
      description: Таблица с пользователями Id:Login
      example:
        '1': Ivan I.
        '2': Konstantin P.
        '3': Alexey B.
    MapId:
      description: Таблица с пользователями и прикрепленной к ним задачами (Id задачи:Id пользователя/ей)
      type: object
      additionalProperties:
        type: array
        items:
          type: integer
          minimum: 1
      example:
        '1':
          - 1
          - 4
          - 5
        '3':
          - 2
        '4':
          - 6
    ListId:
      description: Список с id
      type: array
      items:
        type: integer
      example:
        - 1
        - 2
        - 12
  parameters:
    TaskIdRequest:
      name: id
      description: ID задачи
      in: path
      required: true
      schema:
        type: integer
        example: 4
        minimum: 1
    UserIdRequest:
      name: id
      description: ID пользователя
      in: path
      required: true
      schema:
        type: integer
        example: 5
        minimum: 1
