openapi: 3.0.0
# redocly preview-docs spec.yaml --port 1234
# redocly bundle spec.yaml --output bundled.yaml
info:
  title: TaskManager API
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Локальный сервер
security:
  - CookieAuth: []

tags:
  - name: Auth
    description: Аутентификация и сессии
  - name: Users
    description: Управление пользователями
  - name: Tasks
    description: Управление задачами
  - name: Assignment
    description: Вся бизнес-логика назначения и распределения

paths:
  /tasks:
    $ref: './paths/tasks.yaml#/paths/~1tasks'
  /tasks/all:
    $ref: './paths/tasks.yaml#/paths/~1tasks~1all'
  /tasks/{id}:
    $ref: './paths/tasks.yaml#/paths/~1tasks~1{id}'
    
  /auth:
     $ref: './paths/auth.yaml#/paths/~1auth'

  /users:
    $ref: './paths/users.yaml#/paths/~1users'
  /users/all:
    $ref: './paths/users.yaml#/paths/~1users~1all'
  /users/{id}:
    $ref: './paths/users.yaml#/paths/~1users~1{id}'

  /assign:
    $ref: './paths/assignment.yaml#/paths/~1assign'
  /assign/user/{id}:
    $ref: './paths/assignment.yaml#/paths/~1assign~1user~1{id}'

components:
  securitySchemes:
    CookieAuth:
      type: apiKey
      in: cookie
      name: session_token
      description: Токен аутентификации в cookie. Получать токен через POST /auth/login!